branches:
  - master

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.venv
    volumes:
      - /tmp/cache:/cache

  build:
    image: python:3.6
    commands:
      - pip install virtualenv virtualenvwrapper
      - virtualenv .venv
      - . .venv/bin/activate && pip install -r app/requirements/prod.txt
      - . .venv/bin/activate && pip install -r app/requirements/dev.txt
      - .venv/bin/flake8 app test locustfile.py
      - SETTINGS_MODULE=app.conf.ci .venv/bin/pytest -x

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./venv
    volumes:
      - /tmp/cache:/cache

  publish:
    image: plugins/docker
    repo: yegorLitvinov/metric-back
    secrets: [ docker_username, docker_password ]
    tags: latest
    file: app/Dockerfile

  deploy:
    image: appleboy/drone-ssh
    host: 195.201.27.44
    username: metric
    port: 22
    secrets: [ ssh_password ]
    script:
      - git pull
      - docker-compose pull
      - docker-compose up -d

services:
  pg:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=metric
      - POSTGRES_USER=metric
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine
