language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements/dev.txt

before_script:
  - 'psql -U postgres < sql/init_ci.sql'

script: PYTHONPATH=`pwd` SETTINGS_MODULE=app.conf.ci pytest
